version: '3.7'

services:
  workspace:
    build: .
    restart: always
    container_name: workspace
    volumes:
      - D:\liveProjects\support-ticket-testing\php.ini:/usr/local/etc/php/php.ini
      - D:\liveProjects\support-ticket-testing:/var/www/html
    ports:
      - "8500:8000" # Map container port 8000 to host port 8500
    command: php artisan serve --host=0.0.0.0 --port=8000
    networks:
      - internal

  db:
    image: mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      internal:
        ipv4_address: '172.101.0.7'
    container_name: db

  phpmyadmin:
    image: phpmyadmin
    restart: always
    container_name: phpmyadmin
    ports:
      - "${PHPMYADMIN_PORT}:80"
    environment:
      - PMA_HOSTS=db
      - PMA_PORT=${DB_PORT}
      - PMA_USER=${DB_USERNAME}
      - PMA_PASSWORD=${DB_PASSWORD}
      - PMA_ARBITRARY=1
    networks:
      - internal

  maildev:
    image: maildev/maildev
    restart: always
    container_name: maildev
    environment:
      - TZ=Asia/Kathmandu
      - MAILDEV_WEB_PORT=1080
      - MAILDEV_SMTP_PORT=1025
    ports:
      - "1080:1080"
      - "1025:1025"
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
    networks:
      - internal

networks:
  internal:
    driver: bridge
    ipam:
      config:
        - subnet: 172.101.0.0/16
          gateway: 172.101.0.1

volumes:
  mysql-data:
